# Generated by Django 6.0.3 on 2026-03-25 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.categoria', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['tipo'], name='categoria_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['user'], name='categoria_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'tipo', 'user')},
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['data'], name='lancamento_data_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['tipo'], name='lancamento_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['categoria'], name='lancamento_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['user'], name='lancamento_user_idx'),
        ),
    ]
